- README.md
> docs: #1 README 수정

- .gitignore
> [setting] : #12 gitignore 생성

- perflow-backend/src/main/java/com/touchdown/perflowbackend/annual/command/domain/aggregate/Annual.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/approve/command/domain/aggregate/ApproveLine.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/approve/command/domain/aggregate/ApproveSbj.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/approve/command/domain/aggregate/Doc.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/approve/command/domain/aggregate/DocShareObj.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/approve/command/domain/aggregate/FavTemplate.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/approve/command/domain/aggregate/Status.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/approve/command/domain/aggregate/Template.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/approve/command/domain/aggregate/TemplateField.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/file/command/domain/aggregate/File.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/leave/command/domain/aggregate/Leave.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/domain/aggregate/Notification.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/overtime/command/domain/aggregate/Overtime.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/travel/command/domain/aggregate/Travel.java
appove 폴더에 하나로 묶고
속성들 수정 했습니다. ex) Instant -> LocalDatetime, String -> Status 등
> Setting/#18 결재 엔터티 수정

- perflow-backend/src/main/java/com/touchdown/perflowbackend/department/command/domain/aggregate/Department.java
> chore: #26 부서 엔터티 상위부서 nullable로 수정

- perflow-backend/src/main/java/com/touchdown/perflowbackend/announcement/command/domain/aggregate/Announcement.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/approve/command/domain/aggregate/ApproveSbj.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/approve/command/domain/aggregate/DocShareObj.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/domain/aggregate/Employee.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Appoint.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Authority.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Company.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Department.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Job.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Position.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/menu/command/domain/aggregate/Menu.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/domain/aggregate/Notification.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfoquestion/command/domain/aggregate/Perfoquestion.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/weight/command/domain/aggregate/Weight.java
- 사원 패키지 제외하고 회사, 부서, 직책, 직위, 인사발령, 권한 엔터티 한개의 패키지로 묶었습니당
> [setting/hr] #29 인사정보 관리 패키지 구조 변경

- perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/domain/aggregate/Notification.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/AiPerfoSummary.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/Grade.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/GradeRatio.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/HrPerfo.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/HrPerfoHistory.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/HrPerfoInquiry.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/Kpi.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/KpiCurrentStatus.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/KpiProgressStatus.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/KpiStatus.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/PassStatus.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/Perfo.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/PerfoType.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/Perfoquestion.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/PersonalType.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/QuestionType.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/Weight.java
> setting: #38 인사평가 엔터티 수정 및 통합

- perflow-backend/src/main/java/com/touchdown/perflowbackend/announcement/command/application/controller/AnnouncementCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/announcement/command/application/service/AnnouncementCommandService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/announcement/command/domain/aggregate/Announcement.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/announcement/command/domain/repository/AnnouncementCommandRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/domain/aggregate/Notification.java
공지사항 수정, 삭제 기능 구현
엔티티 기본 생성자 접근 제한 설정
> [feat/announcement]: 공지사항 수정, 삭제 기능 구현

- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/AiPerfoSummary.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/GradeRatio.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/HrPerfo.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/HrPerfoHistory.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/HrPerfoInquiry.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/Kpi.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/KpiLimit.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/KpiProgressStatus.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/KpiStatus.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/Perfo.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/Perfoquestion.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/application/controller/PerfomanceKPIController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/application/dto/KPIDetailResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/application/dto/KPIListResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/application/service/PersonalKPIQueryService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/domain/repository/KPIQueryRepository.java
> [setting/#47]: 인사관리 엔터티 수정 및 신규 엔터티 추가

- perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerformanceKPICommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/KPIDetailRequestDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/service/KPICommandService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/Kpi.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/repository/KpiCommandRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/infrastructure/repository/KpiKpiRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/mapper/PerformanceMapper.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceKPIQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/PersonalKPIQueryService.java
> [feat/perfo/#60]: 개인 KPI CRUD 구현

- perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerformanceKPIPersonalCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerformanceKPITeamCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/service/KPICommandService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceKPIPersonalQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceKPITeamQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/KPIQueryService.java
> [feat/perfo/#70]: 팀 KPI CRUD 구현

- perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerformanceEvaluationColleagueCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/EvalutionDetailDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/EvalutionListDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/service/EvalutionCommandService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/service/KPICommandService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/Perfo.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/repository/KpiCommandRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/repository/PerfoCommandRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/repository/PerfoQuestionCommandRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/infrastructure/repository/EvaEvalutionRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/infrastructure/repository/QuestionCommandRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/mapper/PerformanceMapper.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceEvaluationCollagueQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/EvaAnswerResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/EvaDetailResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/EvaQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/EvaQueryService.java
> [feat/perfo/#72] : 동료 평가 CRU 기능 구현

- perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerfomanceEvaluationColleagueQuestionCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerformanceEvaluationColleagueCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/CreateQuestionRequestDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/UpdateQuestionRequestDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/service/EvalutionCommandService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/Perfoquestion.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/repository/PerfoCommandRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/mapper/PerformanceMapper.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerfomanceEvaluationCollagueQuestionQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/EvaQuestionDetailResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/EvaQuestionRequestDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/EvaQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/EvaQueryService.java
> [feat/perfo/#89] :동료 평가 문항 CRUD 구현

- perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerformanceEvaluationDownwardCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/CreateQuestionRequestDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/EvalutionDetailDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/EvalutionListDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/UpdateQuestionRequestDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceEvaluationDownwardQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/EvaAnswerResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/EvaDetailResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/EvaQuestionDetailResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/EvaQuestionRequestDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/KPIDetailResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/KPILimitResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/KPIListResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/EvaQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/EvaQueryService.java
> [feat/perfo/#94] : 하향 평가 CRU 구현

- perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerfomanceEvaluationDownwardQuestionCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerfomanceEvaluationDownwardQuestionQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/EvaQueryService.java
[feat/perfo/#96] :하향 평가 문항 CRUD 구현
> [feat/perfo/#96] :하향 평가 문항 CRUD 구현

- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/controller/EmployeeQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/Mapper/HrMapper.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/controller/HrQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/dto/DepartmentListResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/service/HrQueryService.java
- 트리 구조 생성시 필요한 서비스 로직만 추가했습니다. >> 부서 전체 목록 조회
> [feat/hr] : #90 전체 부서 정보 조회 서비스 로직  구현

- perflow-backend/src/main/java/com/touchdown/perflowbackend/notification/command/domain/aggregate/Notification.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/controller/ExcelTemplateCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/service/ExcelTemplateCommandService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/service/PayrollCommandService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/aggregate/Payroll.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/aggregate/PayrollDetail.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/aggregate/SeverancePay.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/aggregate/SeverancePayDetail.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/repository/PayrollCommandRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/controller/ExcelTemplateQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/controller/PayrollQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/repository/PayrollQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/PayrollQueryService.java
특정 급여대장 업로드 기능을 구현하고 이외에는 하나의 급여대장과 퇴직금에 여러 데이터가 들어가도록하기 위해 기존 payroll과 severance_pay 테이블을 payroll_detaill과 severance_pay_deatail로 수정하고 새로운 payroll과 severance_pay 테이블 생성
> [feat/payment] : #64 특정 급여대장 업로드

- perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/Mapper/EmployeeMapper.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/controller/EmployeeCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/dto/EmployeeCreateDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/dto/EmployeePwdCreateDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/dto/EmployeeStatusUpdateDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/dto/EmployeeUpdateRequestDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/dto/MyInfoUpdateDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/mapper/EmployeeMapper.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/service/EmployeeCommandService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/domain/aggregate/Employee.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/controller/EmployeeQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/dto/EmployeeDetailResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/dto/EmployeeQueryResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/repository/EmployeeQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/service/EmployeeQueryService.java
> [feat/hr] #104 사원 CRU 기능 구현

- perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/domain/aggregate/Employee.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/Mapper/DepartmentMapper.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/controller/CompanyCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/controller/DepartmentCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/dto/company/CompanyAnnualCountUpdateDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/dto/company/CompanyCreateRequestDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/dto/company/CompanyPaymentDatetimeUpdateDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/dto/company/CompanyUpdateRequestDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/dto/department/DepartmentCreateDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/dto/department/DepartmentUpdateDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/mapper/CompanyMapper.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/mapper/DepartmentMapper.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/service/CompanyCommandService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/service/DepartmentCommandService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Company.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Department.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Job.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Pic.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Position.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/repository/DepartmentCommandRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/repository/PicCommandRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/infrastructure/repository/JpaPicCommandRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/service/HrQueryService.java
- 부서 등록/수정 기능 구현 
- 부서 담당자 엔터티 생성
> [feat/hr] #102 부서 등록/수정 기능 구현 

- perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/domain/aggregate/Employee.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/repository/EmployeeQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/controller/SeveranceExcelTemplateCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/controller/SeverancePayCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/service/SeveranceExcelTemplateCommandService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/service/SeverancePayCommandService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/aggregate/SeverancePay.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/aggregate/SeverancePayDetail.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/repository/SeverancePayCommandRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/infrastructure/repository/JpaSeverancePayRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/controller/PayrollQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/controller/SeveranceExcelTemplateQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/controller/SeverancePayQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/repository/PayrollQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/repository/SeverancePayQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/PayrollQueryService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/SeveranceExcelTemplateQueryService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/SeverancePayQueryService.java
퇴직금 정보를 엑셀 템플릿으로 업로드/다운로드
수정 시 엑셀 파일 업로드/다운로드
> [feat/payment/#111]: 퇴직금 정보 엑셀 파일로 업로드/다운로드

- perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/domain/aggregate/Employee.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/dto/EmployeeDetailResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/controller/JobCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/dto/job/JobCreateDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/dto/job/JobUpdateDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/mapper/JobMapper.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/service/JobCommandService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Job.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/repository/JobCommandRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/controller/JobQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/dto/JobResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/repository/JobQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/service/JobQueryService.java
> [feat/hr]: #118 직책 CRUD 구현

- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/service/SeverancePayCommandService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/controller/SeverancePayQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/dto/SeverancePayDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/dto/SeverancePayDetailResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/dto/SeverancePayListResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/dto/SeverancePayResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/dto/SeverancePayStubDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/dto/SeverancePayStubDetailDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/repository/SeverancePayQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/SeverancePayQueryService.java
퇴직금 리스트 조회
퇴직금 상세조회
퇴직금 명세서 조회
> [feat/payment/#120]: 퇴직금 조회

- perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/domain/aggregate/Employee.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/controller/AppointCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/dto/Appoint/AppointCreateDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/mapper/AppointMapper.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/service/AppointCommandService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Appoint.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Type.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/repository/AppointCommandRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/infrastructure/repository/JpaAppointCommandRepository.java
> [feat/hr] #125 발령 정보 등록 기능 구현

- perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/repository/EmployeeQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/controller/PayrollCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/controller/SeverancePayCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/service/PayrollCommandService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/application/service/SeverancePayCommandService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/aggregate/PayrollDetail.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/aggregate/SeverancePayDetail.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/repository/PayrollCommandRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/repository/SeverancePayCommandRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/controller/PayrollQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/controller/SeverancePayQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/ExcelTemplateQueryService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/SeveranceExcelTemplateQueryService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/SeverancePayQueryService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/dto/ThreeMonthOvertimeDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/repository/WorkAttitudeOvertimeQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/service/WorkAttitudeOvertimeQueryService.java
> [feat/payment/#124]: 퇴직금 조회

- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/PayrollQueryService.java
급여대장 리스트 조회에서 사원의 상태가 ACTVIE인 상태의 사원들의 정보만 조회
> [chore/payment/#134]: 급여대장 리스트 조회 수정

- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerfomancceRatioCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/CreateGradeRatioRequestDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/service/RatioCommandService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/GradeRatio.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/repository/GradeCommandRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/infrastructure/repository/GradeRatioRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/mapper/PerformanceMapper.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerfomanceRatioQueryCommand.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/RatioGradeResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/GradeRatioQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/WeightQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/RatioQueryService.java
> [feat/perfo/#144]: 등급 비율 기능 구현

- perflow-backend/src/main/java/com/touchdown/perflowbackend/menu/command/domain/aggregate/Menu.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/menu/query/application/controller/MenuQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/menu/query/application/dto/MenuResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/menu/query/application/mapper/MenuMapper.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/menu/query/application/repository/MenuQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/menu/query/application/service/MenuQueryService.java
> [feat/menu] : #136 menu조회 기능 구현

- perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerformanceEvaluationPassCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerformanceHumanResourceInquiryCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerformanceKPIPassCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerformanceRatioCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/CreateKpiPassDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/CreatePerfoAdjustmentDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/service/EvalutionCommandService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/service/KPICommandService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/HrPerfoHistory.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/Kpi.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/KpiProgressStatus.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/repository/KpiProgressCommandRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/infrastructure/repository/KpiProgressRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/mapper/PerformanceMapper.java
> [feat/perfo/#146]: KPI 최신화, 평가 조정 기능 구현

- perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/common/util/QRCodeGenerator.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/repository/EmployeeQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/application/controller/WorkAttitudeAttendanceCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/application/controller/WorkAttitudeOvertimeCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/application/controller/WorkAttitudeQRCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/application/dto/WorkAttitudeAttendanceRequestDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/application/dto/WorkAttitudeAttendanceSummaryRequestDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/aggregate/Attendance.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/mapper/WorkAttitudeAttendanceMapper.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/controller/WorkAttitudeAttendanceQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/controller/WorkAttitudeOvertimeQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/controller/WorkAttitudeTravelQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/dto/WorkAttitudeAttendanceResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/dto/WorkAttitudeAttendanceSummaryResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/repository/WorkAttitudeAttendanceQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/service/WorkAttitudeAttendanceQueryService.java
권한별 근무시간 조회 기능입니다.
사원은 본인의 근무 시간
팀장은 본인 포함 해당 팀의 근무 시간
인사팀은 모든 사람들의 근무 시간을 조회할 수 있습니다.
> [feat/attendance/#133]: 권한별 근무 시간 조회 기능 

- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/controller/PayrollQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/controller/SeverancePayQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/dto/PayrollChartWithYearDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/repository/PayrollQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/PayrollQueryService.java
> [chore/payment/#153]: 3년간 급여 데이터 조회 수정

- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/controller/EmployeeQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/dto/EmployeeResponseList.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/repository/EmployeeQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/service/EmployeeQueryService.java
> [feat/hr] : #152 사원 검색기능 구현, 페이지네이션 구현

- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/KPIDetailResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIQueryRepository.java
> [chore/perfo] : #161 Kpi 리스트 호출 기능 수정

- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/KpiCurrentStatus.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIQueryRepository.java
> [chore/perfo] : #166 Kpi status, 쿼리문 수정

- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/PayrollQueryService.java
> [feat/payment/#169]: 정렬 설정

- perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/dto/EmployeeCreateDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/service/EmployeeCommandService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/domain/aggregate/Employee.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/domain/aggregate/EmployeeStatus.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/controller/EmployeeQueryController.java
> [feat/hr] #160 CSV 템플릿 파일 다운로드 기능 구현

- perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerfomanceKPIPassCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/controller/PerformanceKPICurrentCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/CreateKpiProgressDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/service/KPICommandService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/HrPerfoInquiry.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/Kpi.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/KpiStatus.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/PassStatus.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/repository/KpiStatusCommandRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/infrastructure/repository/KpiStatusRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/mapper/PerformanceMapper.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerfomanceKPIPassQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/KPIListResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/KPIRejectReponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIStatusQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/KPIQueryService.java
> [feat/perfo] : #171 KPI 처리 기능 구현

- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/controller/EmployeeCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/service/EmailService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/service/EmployeeCommandService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/security/util/JwtUtil.java
비밀번호 등록 시 발급된 토큰 유효성 검사 추가.
검사 후 등록 페이지로 리다이렉트.
사원 초기 등록시 PENDING 비밀번호 등록시 ACTIVE
> [feat/hr] : #175 비밀번호 등록 기능 추가 구현

- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/KPIDetailResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIQueryRepository.java
> [chore/perfo] : #177 KPI 조회 시 kpiId 조회 가능 수정

- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/KPIDetailRequestDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/Kpi.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIStatusQueryRepository.java
> [chore/perfo] : #179 KPI 수정 시 상태 변경 추가

- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/KPIDetailResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIQueryRepository.java
> [chore/perfo] : #184 KPI 수정 시 상태 변경 추가

- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/controller/EmployeeQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/controller/PositionCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/dto/job/JobCreateDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/dto/position/PositionCreateDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/mapper/AppointMapper.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Appoint.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Job.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Position.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/controller/AppointQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/controller/JobQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/controller/PositionQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/dto/AppointResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/dto/AppointResponseListDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/dto/JobResponseListDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/dto/PositionResponseListDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/repository/AppointQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/service/AppointQueryService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/service/JobQueryService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/service/PositionQueryService.java
> [feat/hr] : #188 직위/직책 페이징 구현, 발령정보 조회 구현

- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/application/dto/KPIDetailRequestDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/domain/aggregate/Kpi.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/command/mapper/PerformanceMapper.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceKPIPersonalQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceKPITeamQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/KPIDetailResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/dto/KPIPeriodRequestDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/KPIQueryService.java
> [feat/perfo] : #187 KPI CRUD 추가 및 수정

- perflow-backend/src/main/java/com/touchdown/perflowbackend/approval/command/domain/repository/ApproveSbjCommandRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/ErrorCode.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/common/exception/SuccessCode.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/query/repository/EmployeeQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/application/controller/WorkAttitudeAnnualCommandController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/application/dto/WorkAttitudeAnnualRequestDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/application/service/WorkAttitudeAnnualCommandService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/aggregate/Annual.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/aggregate/AnnualRetroactiveStatus.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/aggregate/AnnualType.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/domain/repository/WorkAttitudeAnnualCommandRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/infrastructure/repository/JpaWorkAttitudeAnnualRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/command/mapper/WorkAttitudeAnnualMapper.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/controller/WorkAttitudeAnnualQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/dto/WorkAttitudeAnnualResponseDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/repository/WorkAttitudeAnnualQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/workAttitude/query/service/WorkAttitudeAnnualQueryService.java
현재 연차 사용을 했다고 판단하는 기준은 신청한 해당 날짜가 지나면 사용했다고 계산이 되는 방식으로 구현 
조회부분은 jpa로 해결
> [feat/attitude]/#154: 연차 crud 구현

- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/aggregate/PayrollSpecifications.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/ExcelTemplateQueryService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/PayrollQueryService.java
> [chore/payment/#197]: 검색기능 조회 수정

- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceKPIPersonalQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceKPITeamQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/KPIQueryService.java
> [feat/perfo] : #195 KPI 기간별 조회 구현 및 수정

- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceKPIPersonalQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceKPITeamQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/KPIQueryService.java
> [feat/perfo] : #201 KPI 기간별 조회 수정

- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/command/domain/aggregate/PayrollSpecifications.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/payment/query/service/SeverancePayQueryService.java
급여대장 내 검색 조건 수정
퇴직금 상세 조회 타입 변환 수정
> [chore/payment/#208]: 자잘한 수정

- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceKPIPersonalQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/controller/PerformanceKPITeamQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/repository/KPIQueryRepository.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/perfomance/query/service/KPIQueryService.java
> [chore/perfo/#203]: KPI 기간별 조회 수정

- perflow-backend/src/main/java/com/touchdown/perflowbackend/file/command/application/service/FileService.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/controller/AppointQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/controller/JobQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/query/controller/PositionQueryController.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/security/config/SecurityConfig.java
- perflow-backend/src/main/resources/application.yml
- 배포 시 secret을 aws로 저장 후 파드에 환경변수로 전달해주기 때문에 거기에 맞게 application.yaml 파일 수정했습니다.
**api-key 공유 스레드 확인하고 변경해주셔야 로컬에서 돌아갈거에요**
> [deploy] #227 배포 환경에 맞게 설정 변경

- .github/workflows/main.yml
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/application/dto/EmployeeUpdateRequestDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/employee/command/domain/aggregate/Employee.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/application/dto/job/JobUpdateDTO.java
- perflow-backend/src/main/java/com/touchdown/perflowbackend/hr/command/domain/aggregate/Job.java
main에 머지하면서 확인하려면 넘 번거로워서 바꿨슴니다
> [feat/hr] #232 dto 일부 수정. workflow test용으로 수정

- perflow-backend/src/test/java/com/touchdown/perflowbackend/workAttitude/command/application/service/WorkAttitudeOvertimeCommandServiceTest.java
> [chore/attitude/#239] test code 수정

- .github/workflows/main.yml
> [deploy] workflow 진짜 마지막 수정
